version: '3'
services:
#  postgres:
#    ports:
#      - "5432:5432"
#
#  elastic:
#    ports:
#      - "9200:9200"
#
#  etl:
#    restart: 'no'
#
#  fastapi:
#    ports:
#      - "8000:8000"
#    restart: 'no'
#
#  redis:
#    ports:
#      - "6379:6379"

  auth:
    ports:
      - "5000:5000"
    restart: 'no'

  auth_redis:
    ports:
      - "63791:6379"

  auth_postgres:
    ports:
      - "5432:5432"
