version: '3'
services:
  postgres:
    ports:
      - "5432:5432"

  elastic:
    ports:
      - "9200:9200"

  etl:
    restart: 'no'

  fastapi:
    ports:
      - "8000:8000"
    restart: 'no'

  redis:
    ports:
      - "6379:6379"

  auth:
    ports:
      - "5000:5000"
    restart: 'no'

  auth_redis:
    ports:
      - "6380:6379"

  auth_postgres:
    ports:
      - "5433:5432"

  auth_postgres_test:
    image: postgres:14.4
    environment:
          - POSTGRES_PASSWORD=${AUTH_POSTGRES_PASSWORD}
          - POSTGRES_USER=${AUTH_POSTGRES_USER}
          - POSTGRES_DB=${AUTH_POSTGRES_DB}
    ports:
      - "5434:5432"
    healthcheck:
      test: pg_isready -q --port=5432 --dbname=${AUTH_POSTGRES_DB} --username=${AUTH_POSTGRES_USER}
      interval: 2s
      timeout: 2s
      retries: 5
